### ISSUE TITLE
net.bytesPerSecond derives from Total kBytes rather than BytesPerSec

### ISSUE THREAD

**Issue by dedayoa** [newrelic/nri-apache#66]
## Description
My understanding of Total kBytes is the total data transferred while BytesPerSec the transfer rate.
https://github.com/omnigroup/Apache/blob/526ef6bb9f1988be6583cecea96598b6cb1b0d6b/httpd/modules/generators/mod_status.c#L434
https://github.com/omnigroup/Apache/blob/526ef6bb9f1988be6583cecea96598b6cb1b0d6b/httpd/modules/generators/mod_status.c#L449

## Expected Behavior
getRates should be derived from BytesPerSec
https://github.com/newrelic/nri-apache/blob/0fabf42b9f1f4ec23575afa9ce5ee8b907ef4a20/src/metrics.go#L23

## Your Environment
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   Oct  8 2020 21:27:40

**Comment by gsanchezgavier** [comment]
Hi @dedayoa , this metric has a `RATE` type which is automatically computing the change rate of the counter total bytes.
[Here](https://github.com/newrelic/infra-integrations-sdk/blame/master/docs/tutorial.md#L372) is more info about this.
